# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d144ba4ce2d9ff8a6e3fde24565d23df"
name = "85ai"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_customers,write_customers,read_products,unauthenticated_read_product_listings"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://localhost:3000/auth/callback" ]
